{
 "title": "Server",
 "time": { "from": "now-5d", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "environment", "query": { "query": "label_values(env)" } }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "timeseries",
   "description": "The 24 hour rolling percentage of pure availability over the network without considering quality of service.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * avg_over_time(\n  max by (env, job) (\n    avg_over_time(\n      (\n        up{env=\"$env\", job=\"splits_server\"} # record 1 if the service is up\n        or\n        (absent(up{env=\"$env\", job=\"splits_server\"}) * 0) # record 0 if the service is down\n      )[5m:]\n    )\n  )[1d:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usability",
   "type": "timeseries",
   "description": "The 24 hour rolling percentage of usability considering quality of service, e.g. successful vs all requests.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 * avg_over_time(\n    (\n      (sum(rate(http_request_duration_seconds_count{job=\"splits_server\", env=\"$env\", middleware=\"root\", code=~\"2..|3..\"}[5m])) OR vector(0)) # record the amount of successful requests, or 0\n      /\n      (sum(rate(http_request_duration_seconds_count{job=\"splits_server\", env=\"$env\", middleware=\"root\", code!=\"\"}[5m])) OR vector(1)) # record the amount of all requests, or 1\n    )[1d:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "description": "The quantity of throughput stacked by status code, e.g. yellow and red shades imply failure.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{job=\"splits_server\", env=\"$env\", code!=\"\"}[5m]))",
     "legendFormat": "status code {{code}}"
    }
   ]
  },
  {
   "title": "Request Latency Percentiles",
   "type": "timeseries",
   "description": "The desirable and failed user experience in terms of latency, e.g. everything above 500 ms is a failure.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99, \n    sum by(le) (\n        rate(http_request_duration_seconds_bucket{job=\"splits_server\", env=\"$env\", middleware=\"root\"}[5m])\n    )\n)\n",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(\n    0.95, \n    sum by(le) (\n        rate(http_request_duration_seconds_bucket{job=\"splits_server\", env=\"$env\", middleware=\"root\"}[5m])\n    )\n)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(\n    0.90, \n    sum by(le) (\n        rate(http_request_duration_seconds_bucket{job=\"splits_server\", env=\"$env\", middleware=\"root\"}[5m])\n    )\n)",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(\n    0.50, \n    sum by(le) (\n        rate(http_request_duration_seconds_bucket{job=\"splits_server\", env=\"$env\", middleware=\"root\"}[5m])\n    )\n)",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Failures per Second",
   "type": "timeseries",
   "description": "The quantity of failed requests stacked by status code, e.g. all 400 and 500 status codes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(code) (rate(http_requests_total{job=\"splits_server\", env=\"$env\", code=~\"4..|5..\"}[5m]))",
     "legendFormat": "status code {{code}}"
    }
   ]
  },
  {
   "title": "Failure Latency Percentiles",
   "type": "timeseries",
   "description": "The failed user experience in terms of latency, e.g. all 400 and 500 status codes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99, \n    sum by(le) (\n        rate(http_request_duration_seconds_bucket{job=\"splits_server\", env=\"$env\", middleware=\"root\", code=~\"4..|5..\"}[5m])\n    )\n)\n",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(\n    0.95, \n    sum by(le) (\n        rate(http_request_duration_seconds_bucket{job=\"splits_server\", env=\"$env\", middleware=\"root\", code=~\"4..|5..\"}[5m])\n    )\n)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(\n    0.90, \n    sum by(le) (\n        rate(http_request_duration_seconds_bucket{job=\"splits_server\", env=\"$env\", middleware=\"root\", code=~\"4..|5..\"}[5m])\n    )\n)",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(\n    0.50, \n    sum by(le) (\n        rate(http_request_duration_seconds_bucket{job=\"splits_server\", env=\"$env\", middleware=\"root\", code=~\"4..|5..\"}[5m])\n    )\n)",
     "legendFormat": "50th percentile"
    }
   ]
  }
 ]
}